services:
  mysqldb:
    image: mysql:8.0.40
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $DOCKER_DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DOCKER_DB_DATABASE
    ports:
      - $DOCKER_DB_PORT:$DOCKER_DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - $APP_DOCKER_PORT:$APP_PORT
    stdin_open: true
    tty: true
volumes:
  db:
